### ISSUE TITLE
Method not found: 'VFAudio.Create'

### ISSUE THREAD

**Issue by randomlypickedname** [GreyHak/dsp-drone-clearing#11]
Getting this error when a drone tries to mine: 
![image](https://user-images.githubusercontent.com/37277745/110950848-35710900-82f9-11eb-98a8-8451c59d1b14.png)

This is with the latest game patch, .5932.

**Comment by GreyHak** [comment]
I have confirmed the issue.  Thank you for the report @randomlypickedname

**Comment by GreyHak** [comment]
@randomlypickedname Issue fixed in release v1.2.12
