### ISSUE TITLE
Improve counting of free inventory space

### ISSUE THREAD

**Issue by Therzok** [GreyHak/dsp-drone-clearing#16]
Given the player's inventory grid, you can check whether there are any stone/wood/leaves item slots that are not filled, and do a check if you can fill them up with items the drones are clearing.

**Comment by GreyHak** [comment]
I could, but the benefit just isn't worth it.  I'd have to look at all the item types in the inventory, and their quantities compared to stack limits, then determine what the target item could give, and calculate if there's room in the inventory.  Almost no would would care about that level of accuracy.  I consider the current inventory controls sufficient.
