### ISSUE TITLE
Drones not clearing in some scenario

### ISSUE THREAD

**Issue by Therzok** [GreyHak/dsp-drone-clearing#17]
When there is a build order assigned to drones, but it's out of range, the drones will appear as "order assigned" but they are sitting in the mecha.

**Comment by Therzok** [comment]
![20210408013150_1](https://user-images.githubusercontent.com/109974/113942839-39198200-980a-11eb-80fa-724cddf14f50.jpg)

**Comment by GreyHak** [comment]
What you're describing is the same functionality as if you built something, and moved beyond the build range before the drone is assigned to build the item.  So I consider this an enhancement request.  I'll look into it.

**Comment by GreyHak** [comment]
@Therzok Added in release v1.4.1.  Thank you for the suggestion.

**Comment by Therzok** [comment]
Thank you!
