### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by dnabre** [GreyHak/dsp-drone-clearing#18]
Getting an error with the new update, 0.7.18.6931.  

Redbox OMG!! error. The enable/disable button is there, can be toggled. Other than the button being there, no indication that the mod is doing anything.

DSP_Drone_Clearing  version 1.4.1

Using r2modman. I clear out everything, then installed one mod at a time until I found the one giving errors. Here's the log output (~/AppData/LocalLow/Youthcat Studio/Dyson Sphere Program/output_log.txt) 

(Filename: <815d916ff03d4e4489ea2acc662045fc> Line: 0)

MissingFieldException: Field 'PrebuildData.upEntity' not found.
  at MechaDroneLogic.UpdateTargets () [0x00005] in <815d916ff03d4e4489ea2acc662045fc>:0
  at MechaDroneLogic.GameTick (System.Int64 time, System.Single dt) [0x00047] in <815d916ff03d4e4489ea2acc662045fc>:0
  at Mecha.GameTick (System.Int64 time, System.Single dt) [0x00006] in <815d916ff03d4e4489ea2acc662045fc>:0
  at Player.GameTick (System.Int64 time) [0x00043] in <815d916ff03d4e4489ea2acc662045fc>:0
  at GameData.GameTick (System.Int64 time) [0x0006a] in <815d916ff03d4e4489ea2acc662045fc>:0
  at GameMain.FixedUpdate () [0x000ec] in <815d916ff03d4e4489ea2acc662045fc>:0

(Filename: <815d916ff03d4e4489ea2acc662045fc> Line: 0)

The config is whatever is generated  by default. I haven't changed it. 

r2modman's LogOutput.Log"
[Message:   BepInEx] BepInEx 5.4.5.0 - DSPGAME
[Info   :   BepInEx] Running under Unity v2018.4.12.5889476
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 5 plugins to load
[Warning:   BepInEx] Plugin [Distribute Space Warper 1.0.6.0] targets a wrong version of BepInEx (5.4.9.0) and might not work until you update
[Info   :   BepInEx] Loading [LDBTool 1.8.0]
[Info   :   BepInEx] Loading [RecyclableFuelRod 1.1]
[Info   :   BepInEx] Loading [DSP Drone Clearing 1.4.1]
[Info   :DSP Drone Clearing] Configuration loaded.
[Info   :DSP Drone Clearing] Initialization complete.
[Info   :   BepInEx] Loading [RecycleAccumulator 0.0.1]
[Info   :   BepInEx] Loading [Distribute Space Warper 1.0.6.0]
[Message:   BepInEx] Chainloader startup complete
[Info   :Distribute Space Warper] Loaded!
[Info   :DSP Drone Clearing] Configuration loaded.
[Info   :DSP Drone Clearing] Configuration loaded.

Any other logs or settings that would be helpful, I'll be happy to provide.  Haven't changed any settings manually.

**Comment by FlexibleGames** [comment]
Been trying to fix this. Got it to compile, but all the drones go to one object, clear it, then all go to another. Trying to figure out the quagmire of how the jobs get distributed, but my brain hurts. Hopefully the project dev can update it!

**Comment by GreyHak** [comment]
Thank you for the report @dnabre and @FlexibleGames .  The issue has been fixed in v1.4.2.
