### ISSUE TITLE
Not able to run.

### ISSUE THREAD

**Issue by Docwho1983** [GreyHak/dsp-drone-clearing#21]
New update DSP 0.8.22.9331 make it error out. Thanks really miss having my helping hands to clean up as I do other things. It part of my life package.

**Comment by GreyHak** [comment]
@Docwho1983 The Drone Clearing mod has now been rebuilt for DSP 0.8.22.9331.  This issue should be fixed in v1.4.5.  Thank you for letting me know of the issue.
