### ISSUE TITLE
Drone Clearing crashes on use after last update.

### ISSUE THREAD

**Issue by Gonemad79** [GreyHak/dsp-drone-clearing#22]
It spews red messages on the corner of the screen, mentions sound not found, and update.

Removing mod with Overwolf / Thunderstore and reinstalling does not fix. If the clearing function is toggled off on the UI, game boot, but does not crash. Crash only on use. Last tried 29th October 2021.

**Comment by olet42** [comment]
Indeed

**Comment by GreyHak** [comment]
@Gonemad79  @olet42  The Drone Clearing mod has now been rebuilt for DSP 0.8.22.9331.  This issue should be fixed in v1.4.5.  Thank you for letting me know of the issue.
