### ISSUE TITLE
2 Things

### ISSUE THREAD

**Issue by SGZ-Creations** [GreyHak/dsp-drone-clearing#25]
1.  missing item pickup

This stone / obstical are the only one not being cleared by drones is this some u can fix ?
![image](https://user-images.githubusercontent.com/59801736/150875556-6ce69434-b2bc-4062-97a1-f0a504e50e11.png)

2. Could u move the config to work in r2modman ?
![image](https://user-images.githubusercontent.com/59801736/150876233-ccb7144c-0664-47c8-830d-4d0f225f4a8d.png)

**Comment by GreyHak** [comment]
@SGZ-Creations

1) The game considers the stone that you've identified to be a "pebble".  My mod does not collect pebbles by default, but you can enable it in the config file.

2) The mod already works with r2modman config editor.  Please make sure to install the mod using r2modman, and run the game with mods before navigating to the config editor.

![image](https://user-images.githubusercontent.com/479851/150888985-b2c3932b-ae1f-4451-b53e-3fb1045f5d07.png)

**Comment by SGZ-Creations** [comment]
Yea. All i found was the licens not any configs.

**Comment by SGZ-Creations** [comment]
ty did not see that name
