### ISSUE TITLE
[RFE] Change the color and shape of the icon on the button depending on the status

### ISSUE THREAD

**Issue by TehFreek** [GreyHak/dsp-drone-clearing#28]
It would be nice to see at a glance why clearing isn't occurring rather than needing to hover over the button and read the text. As such, I propose that the color and shape of the icon on the button should be different for each reason that clearing is blocked.

**Comment by GreyHak** [comment]
@TehFreek I've added the option in v2.0.0 to configurably color the icon based on categories of reasons that drones might not be clearing.  Thank you for the idea.
