### ISSUE TITLE
Suggestion - In game notify of drones unable to clear

### ISSUE THREAD

**Issue by cdeath-zz** [GreyHak/dsp-drone-clearing#6]
Now that we have all that done, I just thought of a (hopefully) easy to implement suggestion.  A way to know why drones will not activate for clearing.  My idea is hopefully easy, or maybe you have a better way.

- make the drone icon (the one you use to enable / disable) turn red when drones are unable to work on clearing.
- if you hover over the red icon you will see the reason as to why they cannot clear.

I just was thinking about this because when the drones stop clearing I have to look around as to why since I have no indicator.  (the most recent case was I was at 9 instead of 10 inventory clear.)

Just an idea.  I'd help if I knew anything about how any of this modding works.
Thanks again for this awesome mod.

**Comment by GreyHak** [comment]
@cdeath-zz I love the idea of a status in the tool top.  However, since the mod is almost always blocked on something, I don't like the idea of changing the button color.  I'll see if I can release a status enhancement this evening.

**Comment by cdeath-zz** [comment]
Hey yeah you know best.  I get it, it would be red too much to be useful.  Maybe just no status color and you can hover on the icon to see the status no matter what it is.  Maybe just add it below the other text there with a separator or something.

**Comment by GreyHak** [comment]
@cdeath-zz Enhancement added in v1.2.6
