### ISSUE TITLE
Suggestion - drone polish

### ISSUE THREAD

**Issue by cdeath-zz** [GreyHak/dsp-drone-clearing#8]
Since I have no idea how hard any of this is, feel free to do none, some, or all of these.  
I really think the first 2 (if possible) would really polish it off and make it look like an official part of the game.

- Have drones shoot sparks like the mecha does when harvesting
- Have drones show harvesting progress like mecha
- Add in-game options for drones (really just need ones you may want to change several times, like drone range)

That's all I can think of right now.  I can't even think of new features to suggest because that would take it out of the scope of the mod.   Side note, I've run into zero issues since the latest update.  Thanks again for all the hard work.

EDIT ---
Actually the last thing I can think of is to make the drone clearing have it's own research item.  Low level, maybe blue research.

**Comment by GreyHak** [comment]
@cdeath-zz Harvesting progress like Icarus has just been added in v1.2.9.

**Comment by GreyHak** [comment]
I won't be adding a research requirement because that would need to be added to the save file, and I don't want to do that.  The initial release of this mod saved the drone clearing state in the save file, and that became a problem if the mod was ever uninstalled.  It's not worth it.  Nice thought though.

**Comment by cdeath-zz** [comment]
That's cool you were able to do that, I understand the research thing, and yeah that makes sense.  Something I had not considered is now that the drones have a progress indicator, it makes them easy to spot while they are harvesting.  Maybe when official mod support is added things that modify the save can be revisited if it doesn't break the game by removing it.  
Funny enough, this is the exact reason I picked the mods I'm running right now.  Most of them do not modify the game in a way that needs to be saved so if an update breaks the mods, I can keep playing without worry.

**Comment by GreyHak** [comment]
@cdeath-zz The Drone Clearing mod is compatible with [BepInEx.ConfigurationManager](https://github.com/BepInEx/BepInEx.ConfigurationManager).  So I don't consider it worthwhile to spend the time adding my own GUI.  I'll add a note about compatibility with BepInEx.ConfigurationManager to the README in the next release.

**Comment by GreyHak** [comment]
v1.2.14 improved this mod's compatible with [BepInEx.ConfigurationManager](https://github.com/BepInEx/BepInEx.ConfigurationManager).

**Comment by cdeath-zz** [comment]
Yeah that's cool, since I don't know how hard it is to do stuff like that I figure I just suggest a bunch of things and see what sticks =)  I've actually modified the configuration using the mod manager and it is easy enough to do, just takes a bit more time, but undoubtedly less time than writing code / testing for in-game options.  I had noticed another mod had them so thought I would suggest is all.

**Comment by GreyHak** [comment]
@cdeath-zz Drone torches and sparks have been released in v1.4.0.

**Comment by cdeath-zz** [comment]
That's so neat!  Sorry it took so long for you to do!  It really makes the drones look more like they are working.  Also I noticed one of the updates adds the circle when the drones are flying to the target, love it!
