### ISSUE TITLE
More precise config options?

### ISSUE THREAD

**Issue by metalax** [GreyHak/dsp-drone-clearing#9]
Would it be possible to add a config option specifically for the landing capsule?

Also, is it possible to split the IncludeTrees option into Trees, Dead Trees and Small Plants?

Also, is it possible to split the planets up further so we can select particular planet types to clear or not? Eg. split generic into Mediterranean(Starter world), Prairie, Oceanic Jungle, Red Stone, using the list from the wiki https://dsp-wiki.com/Stars_and_planets.

**Comment by GreyHak** [comment]
@metalax Thank you for the feedback.  I'll look into your suggestions.  The filtering that exists now is based on enums that I know exist and are available easily.  I'll have to see how hard it would be to extract the differences you're referring to.  Would you actually use these settings, or are you just brainstorming?

**Comment by GreyHak** [comment]
The problem I have with implementing these changes at the current time is, I would need to upgrade settings in the ConfigFile, and the BepInEx library doesn't give me any insight into what settings exist in a ConfigFile.  So implementing these changes now would have to replace people's existing settings with new default values.  I would rather not do that if it can be avoided.  So I've asked the developer of BepInEx add an enhancement which will allow me to upgrade these config settings.
https://github.com/BepInEx/BepInEx/issues/203
We'll see where that leads before proceeding with this enhancement request.

**Comment by GreyHak** [comment]
On reflection, I think it's important to add a specific setting to enable/disable space capsule so that its default can be false.  This is important if someone wants stones to be cleared, and sets CollectResources, then starts a new game.  You'd lose those early-game resources.  This will definitely be in the next release.

**Comment by metalax** [comment]
Certainly would use the capsule one to keep the capsule, and I know there are quite a few others who do so.

More specific planet type allows for things like keeping a park like area on your Mediteranean starter world or allowing you to keep the mushrooms of Red Stone worlds, while clearing everything on a Prarie or Jungle.

Splitting up the vegetation types is because sometime I like to clear out the small plants while leaving the trees, and the dead trees sometimes drop Coal and rarely Graphene or Nanotubes, So being able to specifically harvest those would be useful.

**Comment by GreyHak** [comment]
@metalax Windows10CE on Discord helped me get access to the ConfigFile private variables.  So I am able to upgrade the config settings.  With v1.2.11 you now have control over the space capsule separate from stones, and it's defaulted to false, and you have fine-grain control over planets.

**Comment by metalax** [comment]
Thanks for that, seems to be working fine.

One thing I noticed on upgrading to the current version is that the setting for number of empty inventory slots was set back to 10 from where I had previously altered it to 5. All other altered settings carried over fine.

Is there any possibility of splitting the vegetation up by type, or is that not possible?
